# Generated by Django 2.0.5 on 2018-07-10 19:12

from django.db import migrations

def seed_meals(apps, schema_editor):
    Meal = apps.get_model('diary', 'Meal')
    meal = Meal(name = 'Breakfast')
    meal.save()
    meal = Meal(name = 'Snack')
    meal.save()
    meal = Meal(name = 'Lunch')
    meal.save()
    meal = Meal(name = 'Dinner')
    meal.save()

class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_meals),
    ]
